# API Gateway for Ticket System
server.port=9100

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:9101
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=ticket-service
spring.cloud.gateway.routes[1].uri=http://localhost:9102
spring.cloud.gateway.routes[1].predicates[0]=Path=/tickets/**

spring.cloud.gateway.routes[2].id=customer-service
spring.cloud.gateway.routes[2].uri=http://localhost:9103
spring.cloud.gateway.routes[2].predicates[0]=Path=/customer/**

spring.cloud.gateway.routes[3].id=admin-service
spring.cloud.gateway.routes[3].uri=http://localhost:9104
spring.cloud.gateway.routes[3].predicates[0]=Path=/admin/**

spring.cloud.gateway.routes[4].id=executive-service
spring.cloud.gateway.routes[4].uri=http://localhost:9105
spring.cloud.gateway.routes[4].predicates[0]=Path=/executive/**

spring.webflux.static-locations=classpath:/static/
