spring.application.name=api-gateway
server.port=8080

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Gateway Routes Configuration
spring.cloud.gateway.mvc.routes[0].id=user-service
spring.cloud.gateway.mvc.routes[0].uri=lb://user-service
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.mvc.routes[1].id=ticket-service
spring.cloud.gateway.mvc.routes[1].uri=lb://ticket-service
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/tickets/**

# Discovery Locator
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
