@echo off
echo Stopping any running Java services...
taskkill /F /IM java.exe /T 2>nul

echo Syncing UI files to API Gateway...
if not exist microservices\api-gateway\src\main\resources\static mkdir microservices\api-gateway\src\main\resources\static
xcopy /E /Y microservices\ui\* microservices\api-gateway\src\main\resources\static\

echo Starting Ticket System Services...

echo Starting Auth User Service (9101)...
start /B cmd /c "mvn -f microservices\auth-user-service\pom.xml spring-boot:run > auth.log 2>&1"

echo Starting Ticket Service (9102)...
start /B cmd /c "mvn -f microservices\ticket-service\pom.xml spring-boot:run > ticket.log 2>&1"

echo Starting Customer Service (9103)...
start /B cmd /c "mvn -f microservices\customer-service\pom.xml spring-boot:run > customer.log 2>&1"

echo Starting Admin Service (9104)...
start /B cmd /c "mvn -f microservices\admin-service\pom.xml spring-boot:run > admin.log 2>&1"

echo Starting Executive Service (9105)...
start /B cmd /c "mvn -f microservices\executive-service\pom.xml spring-boot:run > executive.log 2>&1"

echo Starting API Gateway (9100)...
start /B cmd /c "mvn -f microservices\api-gateway\pom.xml spring-boot:run > gateway.log 2>&1"

echo.
echo All services are starting up. Please wait 1-2 minutes...
echo You can access the system at http://localhost:9100
echo Check *.log files for any startup issues.
