spring.application.name=api_gateway
server.port=9090

#Eureka specific
eureka.client.service-url.defaultZone=http://localhost:9000/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Enable discovery-based routing
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# CORS Configuration for the Frontend
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*